  
spring:
  application:
    name: intercom-web

spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

server:
  servlet:
    context-path:  /${spring.application.name}
    session:
      timeout: 1800
  port: 8081


  
logging:
  file:  C:/logs/intercom.log