  
spring:
  application:
    name: intercom-web
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

server:
  servlet:
    context-path:  /${spring.application.name}
    session:
      timeout: 1800


  
logging:
  file:  C:/logs/intercom.log